### PR TITLE
Feature/report2

### LINKED ISSUE #10: Create template - Incident Complaint Report 02
Report No.2
- Election Complaints 24 hour summary (Elections Complaint Management Centre)
- create this under **/templates/incidents/complaints/daily_summary_report_categorywise.js**

IMG-2111

### PR DESCRIPTION
**Pull request by arunwij**
This is the initial version of the template report 2. 

TODO: 
1. bind the variables according to the data format
2. add logos to the template
3. put correct Tamil words

please find the attached pdf document here. 

[daily_summery_report_categorywise.pdf](https://github.com/ECLK/pdf-service/files/4260530/daily_summery_report_categorywise.pdf)

### CODE REVIEW

**Comment by MrClemRkz** [comment]
@arunwij can you submit a generated pdf file for this?

**Comment by arunwij** [comment]
Please find the pdf here
 https://github.com/ECLK/pdf-service/files/4260530/daily_summery_report_categorywise.pdf

**Comment by MrClemRkz** [comment]
this is awesome. can we now decide how could we have pdf data be populated? 
check the table 'common_category' to get an idea.

**Comment by arunwij** [comment]
@MrClemRkz I have updated the template to accept values from a JSON object. You can find the [running sample here](https://codesandbox.io/s/suspicious-galileo-63dyu).

**JSON format**
`{
  	date: '2020/05/18',
    categories: [
        {
            categoryNameSinhala: 'ප්‍රචණ්ඩ ක්‍රියා',
            categoryNameTamil: 'வன்முறை',
            subCategories: [
                {
                    name: 'වාචික බිය ගැන්වීම',
                    count: 10
                },
                {
                    name: 'ආයුධ පෙන්වා බිය ගැන්වීම වෙඩි තබා මැරීමට තැත් කිරීම',
                    count: 1
                },
                {
                    name: 'පහර දීම / මැර ප්‍රහාර එල්ල කිරීම',
                    count: 5
                }
            ]
        },
        {
            categoryNameSinhala: 'නීති උල්ලංඝන',
            categoryNameTamil: 'சட்ட மீறல்',
            subCategories: [
                {
                    name: 'මැතිවරණ ප්‍රචාරණ කටයුතු වලට බාධා කිරීම',
                    count: 3
                }
            ]
        }
    ],
    other: 23,		
    total: 35
}`

**Comment by MrClemRkz** [comment]
This is awesome work bro. love it.

**Pull request merged**
